source 'https://rubygems.org'

gem 'mathematical', '~> 1.6', '= 1.6.14'

gem 'cgi'
gem 'citeproc-ruby'
gem 'coderay'
gem 'concurrent-ruby'
gem 'csl-styles'
gem 'iconv'
gem 'json'
gem 'liquid'
gem 'nokogiri'
gem 'pygments.rb'
gem 'rghost'
gem 'rouge'
gem 'tilt'

gem 'asciidoctor'
gem 'asciidoctor-bibtex'
gem 'asciidoctor-diagram'
gem 'asciidoctor-mathematical'
gem 'asciidoctor-pdf'
gem 'asciidoctor-sail'

